// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "Pegefinger":return img`
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
............ff............
...........f11f...........
...........f11f...........
...........f11f...........
...........f11f...........
...........f11fff.........
...........f11f11fff......
...........f11f11f11fff...
.......fff.f11f11f11f11f..
.......f11ff11f11f11f11f..
.......f111f11111f11f11f..
........f11111111111f11f..
........f11111111111111f..
.........f1111111111111f..
..........f111111111111f..
..........f11111111111f...
...........f1111111111f...
............f11111111f....
............fffffffff.....
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
