namespace SpriteKind {
    export const Objective = SpriteKind.create()
}
function Lejlighed () {
    tiles.setCurrentTilemap(tilemap`level3`)
    Hero = sprites.create(img`
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f f e 2 2 2 2 2 2 e e f . . 
        . . f e 2 f f f f f f 2 e f . . 
        . . f f f f e e e e f f f f . . 
        . f f e f b f 4 4 f b f e f f . 
        . f e e 4 1 f d d f 1 4 e e f . 
        . . f e e d d d d d d e e f . . 
        . . . f e e 4 4 4 4 e e f . . . 
        . . e 4 f 2 2 2 2 2 2 f 4 e . . 
        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
        . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `, SpriteKind.Player)
    Hero.setScale(1, ScaleAnchor.Middle)
    Hero.setPosition(151, 120)
    scene.cameraFollowSprite(Hero)
    controller.moveSprite(Hero, 100, 100)
    Router = sprites.create(img`
        ..................
        ..................
        ..................
        .....8888888......
        ....8.......8.....
        ...8.........8....
        ..8...88888...8...
        .....8.....8......
        ....8.......8.....
        .......888........
        ......8...8.......
        .f................
        .f......8.........
        .f................
        ffffffffffffff....
        feebb7b7b4b2bf....
        feebb5b5b5b5bf....
        ffffffffffffff....
        `, SpriteKind.Objective)
    Router.setPosition(200, 109)
}
let Router: Sprite = null
let Hero: Sprite = null
Lejlighed()
